---
server:
    install: '1'
    packages: [git, imagemagick, vim, nodejs, npm]
    timezone: Europe/Brussels
    locale: nl_NL.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: phansible, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: phansible.vb
mongodb:
    install: '1'
php7:
    version: php7.1
    extensions: [php7.1-curl, php7.1-gd, php7.1-intl, php7.1-mbstring, php7.1-tidy, php7.1-xml, php7.1-zip]

