---
- name: Add ppa Repository
  become: yes
  become_method: sudo
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install PHP
  become: yes
  become_method: sudo
  apt: pkg={{item}} state=latest
  with_items:
    - "{{ php7.version }}"
    - "{{ php7.version }}-cli"
    - "{{ php7.version }}-fpm"

- name: Install PHP extensions
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=latest
  with_items: "{{ php7.extensions }}"
  when: php7.extensions is defined