---
- name: Add ppa Repository
  become: yes
  become_method: sudo
  apt_repository: repo=ppa:iacobs/wkhtmltopdf

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install wkhtmltopdf
  become: yes
  become_method: sudo
  apt: pkg=wkhtmltopdf state=latest