- name: Phalcon | Download from Github
  git: repo=https://github.com/phalcon/cphalcon.git dest=/home/vagrant/phalcon version=2.1.x
  become: yes
  become_user: vagrant

- name: Phalcon | Build extension
  shell: /home/vagrant/.composer/vendor/bin/zephir build --backend=ZendEngine3
  args:
    chdir: /home/vagrant/phalcon
  become: yes
  become_user: root

- name: Phalcon | Install extension
  copy:
    src=files/phalcon.ini
    dest=/etc/php/7.0/mods-available/phalcon.ini
    owner=root group=root mode=0644

- name: Phalcon | Enable extension
  shell: phpenmod phalcon
  become: yes
  become_user: root
  notify:
    - restart php7-fpm
    - restart nginx

- name: Phalcon | Install developer tools
  shell: composer global require phalcon/devtools:dev-master
  become: yes
  become_user: vagrant