- name: Phalcon | Download from Github
  git: repo=https://github.com/phalcon/cphalcon.git dest=/home/{{ app.username }}/phalcon
  become: yes
  become_user: "{{ app.username }}"

- name: Phalcon | Build extension
  shell: /home/{{ app.username }}/.composer/vendor/bin/zephir build --backend=ZendEngine3
  args:
    chdir: /home/{{ app.username }}/phalcon
  become: yes
  become_user: root

- name: Phalcon | Install extension
  copy:
    src=files/phalcon.ini
    dest=/etc/php/7.0/mods-available/phalcon.ini
    owner=root group=root mode=0644

- name: Phalcon | Enable extension
  shell: phpenmod phalcon
  become: yes
  become_user: root
  notify:
    - restart php7-fpm
    - restart nginx