---
- name: Zephir | Install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - re2c
    - libpcre3-dev
    - libjson0
    - libjson0-dev
    - gcc
    - make
    - build-essential
    - php7.0-dev
    - php7.0-zip
  become: yes
  become_user: root

- name: Zephir | Install composer package
  shell: composer global require "phalcon/zephir:dev-master"
  become: yes
  become_user: "{{ app.username }}"