---
- name: Zephir | Install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - re2c
    - libpcre3-dev
    - libjson0
    - libjson0-dev
    - "{{ php7.version }}-dev"
  become: yes
  become_user: root

- name: Zephir | Download from Github
  git: repo=https://github.com/phalcon/zephir.git dest=/home/vagrant/zephir
  become: yes
  become_user: vagrant

- name: Zephir | Install
  shell: ./install -c
  args:
    chdir: /home/vagrant/zephir
  become: yes
  become_user: root